In [27]:
import numpy as np

In [28]:
I = np.array([[1,0,0], [0,1,0], [0,0,1]])
u = np.array([[2,5,-3]]).T


np.dot(I, u)

array([[ 2],
       [ 5],
       [-3]])

In [29]:
B = np.array([[2,0,-1], [-2,3,1], [0,4,-1]])


np.dot(B, u)

array([[ 7],
       [ 8],
       [23]])

In [43]:
u2 = np.array([[0, -4, 6]]).T


U = np.hstack((u, u2))
U

array([[ 2,  0],
       [ 5, -4],
       [-3,  6]])

In [44]:
np.dot(B, U)

array([[  7,  -6],
       [  8,  -6],
       [ 23, -22]])