In [1]:
import numpy as np

In [2]:
x = np.array([25, 2, -3, -23])
x.T

array([ 25,   2,  -3, -23])

Respuesta no tiene traspuesta

In [12]:
x = np.array([[25, 2, -3, -23]])
x.T

array([[ 25],
       [  2],
       [ -3],
       [-23]])

Aunque si es un array si que tiene traspuesta

In [13]:
x = np.array([[25], [2], [-3], [-23]])
x.T

array([[ 25,   2,  -3, -23]])

Y la traspuesta del vector columna es la fila

In [11]:
X = np.array([[42, 4, 7, 99], [-99, -3, 17, 22]])

X.shape

(2, 4)

Respuesta tiene 2 filas y 4 columnas (2,4)

In [10]:
X[1][2]

np.int64(17)

Respuesta en python la posicion es la 1,2 pero en notiacion normal esta en la fila 2 y en la columna 3. (2,3) y es el elemento X[2,3]