In [1]:
import numpy as np

In [3]:
A = np.array([[0 ,1, 2], [3, 4 ,5], [6, 7, 8]])

b = np.array([-1, 1, -2])


np.dot(A,b)

array([ -3,  -9, -15])

In [5]:
A = np.array([[1 ,0, 0], [0, 1 ,0], [0, 0, 1]])
b = np.array([-1, 1, -2])


np.dot(A,b)

array([-1,  1, -2])

In [4]:
A = np.array([[0 ,1, 2], [3, 4 ,5], [6, 7, 8]])

B = np.array([[-1, 0], [1, 1], [-2 ,2]])


np.dot(A,B)

array([[ -3,   5],
       [ -9,  14],
       [-15,  23]])