In [2]:
import numpy as np

In [6]:
Y = np.array([[42,4,7,99], [-99,-3, 17, 22]])
Y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [7]:
Y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [9]:
X = np.array([[25, 10], [-2, 1]])
Y = np.array([[-1, 7], [10, 8]])


X * Y

array([[-25,  70],
       [-20,   8]])

In [12]:
w = np.array([-1, 2, -2])
x = np.array([5 ,10, 0])

np.dot(w,x)

np.int64(15)